baseURL: "https://jorjafox.net/"
languageCode: "en-us"
title: "Fans of LeFox"
subtitle: "A fansite celebrating the actor and activist, Jorja Fox"
copyright: "Copyright Fans of LeFox © 1996-2024"

contentDir: "content/posts"
dataDir: "content/data"
staticDir: "content/static"
assetDir: "content/assets"

pluralizelisttitles: "false"
buildFuture: "true"
summaryLength: 10
enableRobotsTXT: true
mainSections: [ "blog" ]

minify:
  disableJS: true
  minifyOutput: false
  tdewolff:
    js:
      keepVarNames: true
      version: 2022
    html:
      keepWhitespace: true

disableKinds: ["taxonomy", "term"]

outputs:
  home: ["HTML", "RSS", "REDIR"]
