
main:
- name: Home
  pageRef: /
  weight: 10
- name: Site News
  pageRef: /blog/
  weight: 20
- name: About
  pageRef: /about/
  weight: 20
- name: FAQs
  pageRef: /faq/
  weight: 20
- name: Resources
  pageRef: /library
  weight: 30
- parent: Resources
  name: Library
  pageRef: /library/
  weight: 31
- parent: Resources
  name: Filmography
  pageRef: /library/filmography/
  weight: 32
- parent: Resources
  name: News Articles
  pageRef: /library/news/
  weight: 33
- parent: Resources
  name: Advocacy
  pageRef: /library/advocacy/
  weight: 34
- parent: Resources
  name: Transcripts
  pageRef: /library/transcript/
  weight: 35

footer:
- name: Links
  weight: 10
- name: Privacy Policy
  parent: Links
  pre: "fas fa-lock"
  pageRef: /tos/privacy/
  weight: 10
- name: Terms of Service
  parent: Links
  pre: "fas fa-file-contract"
  pageRef: /tos/
  weight: 20
- name: Copyright
  parent: Links
  pre: "fas fa-copyright"
  pageRef: /tos/copyright/
  weight: 30
- name: Contribute
  parent: Links
  pre: "fab fa-github"
  params:
      rel: external
  url: https:/github.com/JorjaFox/website/
  weight: 40
- name: RSS Feed
  parent: Links
  pre: "fas fa-rss"
  pageRef: https://jorjafox.net/feed.xml
  weight: 50

social:
- name: Official Website
  url: https://jorjafox.com/
  pre: "fas house-chimney-user"
  weight: 10
- name: X/Twitter
  url: https://twitter.com/jorjafoxofficia/
  pre: "fab x-twitter"
  weight: 20
- name: Facebook
  url: https://www.facebook.com/jorjafoxofficial/
  pre: "fab facebook"
  weight: 30
