
main:
- name: Home
  pageRef: /
  weight: 10
- name: Site News
  pageRef: /blog
  weight: 20
- name: About
  pageRef: /about
  weight: 20
- name: FAQs
  pageRef: /faq
  weight: 20
- name: Resources
  pageRef: /library
  weight: 30
- parent: Resources
  name: Library
  url: /library
  weight: 31
- parent: Resources
  name: Filmography
  url: /library/filmography
  weight: 32
- parent: Resources
  name: News Articles
  url: /library/news
  weight: 33
- parent: Resources
  name: Advocacy
  url: /library/advocacy
  weight: 34
- parent: Resources
  name: Transcripts
  url: /library/transcript
  weight: 35

footer:
- name: Links
  weight: 10
- name: Privacy Policy
  parent: Links
  pageRef: /tos/privacy
  weight: 10
- name: Terms of Service
  parent: Links
  pageRef: /tos/terms
  weight: 20
- name: Copyright
  parent: Links
  pageRef: /tos/copyright
  weight: 30
