
main:
- name: Home
  pageRef: /
  weight: 10
- name: News
  pageRef: /blog
  weight: 20
- name: About
  pageRef: /about
  weight: 20
- name: Library
  pageRef: /library
  weight: 30

footer:
- name: Links
  weight: 10
- name: Privacy Policy
  parent: Links
  pageRef: /tos/privacy
  weight: 10
- name: Terms of Service
  parent: Links
  pageRef: /tos/terms
  weight: 20
- name: Copyright
  parent: Links
  pageRef: /tos/copyright
  weight: 30
