main:
  endorse: false
  description: "A fansite celebrating the actor and activist, Jorja Fox"

head:
  tagline: "A Jorja Fox Fansite"

style:
  primary: "#107952"
  secondary: "#34383C"

navigation:
  logo: "logo.svg"
  size: "lg"

favicon:
  logo: "/img/favicon.png"

home:
  sections: [ "as-seen-on", "blog" ]
  style: "gradient-featured"
  feature:
    width: 6
    color: "primary"

externalLinks:
  cue: true

includeToc:
  show: true

sections:
  as-seen-on:
    title: "As Seen On"
    layout: "nav"
    sort: "weight"
    reverse: false
    style: "justify-content-center as-seen-on"
    pane: "persona"
    width: 100
  blog:
    reference: "More Posts"
    sort: "date"
    layout: "card"
    style: "border-0 shadow card-zoom card-body-margin"
    reverse: true
    title: "Blog Posts"
    cols: 3
    padding: "3"
    header: "full"
    footer: "none"

schema:
  name: "Fans of Lefox"
  twitter: "https://twitter.com/fansoflefox"
  github: "https://github.com/jorjaFox/website/"

modules:
  bs5-lightbox:
    integration: "optional"
    disableTemplate: false
    state: "async"
  katex:
    disableTemplate: true
  leaflet:
    disableTemplate: true
