main:
  endorse: false
  description: "A fansite celebrating the actor and activist, Jorja Fox"

head:
  tagline: "A Jorja Fox Fansite"

style:
  primary: "#107952"

navigation:
  logo: "logo.svg"
  size: "lg"

favicon:
  logo: "/img/favicon.png"

home:
  sections: [ "blog" ]
  feature:
    width: 6
    color: "primary"

externalLinks:
  cue: true

includeToc:
  show: true

sections:
  blog:
    reference: "More Posts"
    sort: "date"
    reverse: true
    title: "Blog Posts"

schema:
  name: "Fans of Lefox"
  twitter: "https://twitter.com/fansoflefox"
  github: "http://github.com/jorjaFox/website/"

modules:
  bs5-lightbox:
    integration: "optional"
    disableTemplate: false
    state: "async"
  katex:
    disableTemplate: true
