main:
  endorse: false

style:
  primary: "#107952"

navigation:
  logo: "flf-logo.svg"
  size: "lg"

favicon:
  logo: "/img/favicon.png"

home:
  sections: [ "blog" ]
  feature:
    width: 4

externalLinks:
  cue: true
