main:
  endorse: false
  description: "A fansite celebrating the actor and activist, Jorja Fox"

head:
  tagline: "A Jorja Fox Fansite"

style:
  primary: "#107952"

navigation:
  logo: "logo.svg"
  size: "lg"

favicon:
  logo: "/img/favicon.png"

home:
  sections: [ "blog" ]
  feature:
    width: 4

externalLinks:
  cue: true


