name: 'Preflight Checks'

on:
  push:

concurrency:
     group: ${{ github.ref }}-ci
     cancel-in-progress: true

jobs:
  preflight-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Do a git checkout including submodules
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Setup Node and Install
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install && npm run mod:update

      #- name: Lint
      #  run: npm run lint

      - name: Make Resources Folder locally
        run: mkdir resources

      - name: Download resources from server
        run: rsync -rlgoDzvc -i ${{ secrets.REMOTE_USER }}@ ${{ secrets.REMOTE_HOST }}:/home/jorjafox/${{ secrets.HUGO_RESOURCES_URL }}/ resources/

      #- name: Build site
      #  run: npm run build

      #- name: Copy back down all the regenerated resources
      #  run: rsync -rlgoDzvc -i --delete resources/ ${{ secrets.REMOTE_USER }}@ ${{ secrets.REMOTE_HOST }}:/home/jorjafox/${{ secrets.HUGO_RESOURCES_URL }}/
